apiVersion: v1                                                                                
kind: PersistentVolume                                                                        
metadata:                                                                                     
  name: wp-pv                                                                              
spec:                                                                                         
  capacity:                                                                                   
    storage: 2Gi     
  accessModes:                                                                                
    - ReadWriteOnce                                                                           
  hostPath:                                                                                   
    path: "/mnt/data1"                                                                    
#---                                                                                           
#apiVersion: v1                                                                                
#kind: PersistentVolumeClaim                                                                   
#metadata:                                                                                     
#  name: wp-pv-claim                                                                        
#spec:                                                                                         
#  accessModes:                                                                                
#    - ReadWriteOnce                                                                           
#  resources:                                                                                  
#    requests:                                                                                 
#      storage: 5Gi
